### ISSUE TITLE
No loader is configured for ".node"

### ISSUE THREAD

**Issue by keuller** [jw-12138/vite-plugin-vsharp#11]
## Environment

- Nuxt 3.2.3
- Vite plugin vsharp 1.4.2

## Error

When I ran `pnpm dev`on Nuxt project I got this error:

```bash
 ERROR  6:35:17 PM [vite] error while updating dependencies:                                                                                          18:35:17
Error: Build failed with 1 error:
node_modules/.pnpm/fsevents@2.3.2/node_modules/fsevents/fsevents.js:13:23: ERROR: No loader is configured for ".node" files: node_modules/.pnpm/fsevents@2.3.2/node_modules/fsevents/fsevents.node
```

When I ran `pnpm build` vshaprt plugin does not find the assets, even the resources exists on the specified path.

```bash
[unhandledRejection] Input file is missing: /workspace/personal/resumeapp/.nuxt/dist/server/start-yellow.png
```

**Comment by jw-12138** [comment]
could you please provide the file/folder structure or an example project?

**Comment by keuller** [comment]
Yes, my structure folder is:
```
[resumeapp]
  - assets
     - check.jpg
     - share.png
     - start-yellow.png
  - pages
     - index.vue 
  - public
     - favicon.ico
```

**Comment by jw-12138** [comment]
it appears that the issue at hand is connected to esbuild, pnpm and sharp. as a Vite plugin developer, my assistance may be limited. however, I can offer some guidance.

You may want to take a look at this issue on GitHub:
https://github.com/evanw/esbuild/issues/1051

especially this comment:
https://github.com/evanw/esbuild/issues/1051#issuecomment-1006992549

I wish this could help you!
