### ISSUE TITLE
Vite 4 support

### ISSUE THREAD

**Issue by JaZo** [jw-12138/vite-plugin-vsharp#14]
First of all, thanks for this helpful plugin! I'm trying to install this plugin in a Nuxt project, as described in https://masteringnuxt.com/blog/compressing-images-with-vite-and-vsharp, but I get conflicting peer dependencies as Nuxt requires Vite 4, and this plugin requires Vite 3 (3.2.7 to be exact). Do you have any plans to support Vite 4? According to [the migration guide](https://vitejs.dev/guide/migration.html) there should be little to no changes required, so maybe it's just a matter of bumping the version? 🤔

**Comment by JaZo** [comment]
I've ignored the peer dependency conflict and it seems to work just fine.

**Comment by jw-12138** [comment]
glad to know you found your way out! i'm going to close this issue if there is no furthur questions.

and holy shxt there is now an article just about how to use my plugin? stressful! 🤣

**Comment by JaZo** [comment]
Well, I do think this should still be addressed by allowing Vite 4 as peer dependency so library users shouldn't need to override your dependencies in order to use this plugin with Vite 4.

**Comment by JaZo** [comment]
Being featured is nice right? 😄

**Comment by jw-12138** [comment]
ok, i've updated the plugin and the peer dependency range has been extended to support Vite versions at `>= 2.6 < 5`. this should resolve the conflict you encountered!

and as you can see i'm not actually very familiar with these kinda stuff, thanks for pointing this out, i'll try to do better!

**Comment by JaZo** [comment]
Thanks, looks good! Don't worry, we're all learning and I'm glad to help!
