### ISSUE TITLE
Security: sharp should be updated to 0.32.6

### ISSUE THREAD

**Issue by AloisSeckar** [jw-12138/vite-plugin-vsharp#15]
`sharp`  dependency is pinned to `0.31.3` in `package.json`

A new vulnerability was discovered in its dependency tree requiring update to `0.32.6`, which cannot be done automatically, as it is not a carret dependency, but a direct one.

![image](https://github.com/jw-12138/vite-plugin-vsharp/assets/7399922/63dc4a58-7545-4e3d-90ef-66c90c87397a)

I believe I can play with dependencies in my project and override the version, but would be better to fix it in the source. I just don't know if it is possible without breaking something in your plugin. That's why I am opening this issue first.

**Comment by jw-12138** [comment]
should be fixed at plugin version 1.6.0! thanks a lot!

**Comment by AloisSeckar** [comment]
Thank you, @jw-12138, for quick fix  👍
