### ISSUE TITLE
Laravel support

### ISSUE THREAD

**Issue by Uzcoin404** [jw-12138/vite-plugin-vsharp#16]
Can I use this plugin in laravel project with laravel-vite-plugin?

**Comment by jw-12138** [comment]
as long as your project has a vite config file and pipes a build stage(`npm run build`), the plugin should work fine with it. i encourage you to give it a try and let me know if you encounter any issues.

**Comment by Uzcoin404** [comment]
In laravel I use function that called asset() to get static images like that 
`<img src="{{ asset('img/header_images/hero.png') }}" alt="">`
So asset() output path be like `public/img/header_images/hero.png` Can plugin really detect this path? 

I'm getting this error when I run `npm run build`

> node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^ 
[Error: Input file is missing: public/img/aboutpublic\buildpng]

But I have never used `public/img/aboutpublic\buildpng` in my code 

Here is my `vite.config.js`

```
import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import vsharp from 'vite-plugin-vsharp';

export default defineConfig({
  plugins: [
    laravel({
      input: [
        "resources/css/style.css",
        "resources/css/app.css",
        "resources/js/app.js",
        "resources/js/script.js",
        "resources/js/cursor_animate.js"
      ],
      // refresh: true,
    }),
    // vsharp()
  ],
});
```

_ps: sorry for my poor english_

**Comment by jw-12138** [comment]
i can kinda get your idea but i think this plugin is not meant to work in this situation.   

from my little experiences in php, paths are often rendered during requests or cached, my suggestion is to use a laravel plugin to compress images or render the site statically and then run the vite build process again.

ps: it's ok, there are a lot of languages in the world, nobody was born to speak english my man, see it as a tool for communications, i understand you, you understand me, and that's enough.👍

**Comment by Uzcoin404** [comment]
Thank you for your advice!
