### ISSUE TITLE
Add Types for the plugin

### ISSUE THREAD

**Issue by kevbook** [jw-12138/vite-plugin-vsharp#17]

**Comment by kevbook** [comment]
Would you prefer if I did a PR? Typescript support is pretty important

**Comment by jw-12138** [comment]
<img width="524" alt="image" src="https://github.com/jw-12138/vite-plugin-vsharp/assets/29943110/2b4bc22c-eff7-4c99-ab08-bcd319ab57db">

1.8.0 has added types, sorry for the long wait🥶, PRs are welcome if you think there is still something missing!
