### ISSUE TITLE
sfunc is not a function

### ISSUE THREAD

**Issue by nsouto** [jw-12138/vite-plugin-vsharp#3]
Hello,

I'm running into this issue when running `vite build` and was hoping you can shed some light on it:

```
node_modules/vite-plugin-vsharp/d/vsharp.js:225
  (0, _sharp["default"])(img)[sfunc](opts[extname]).toBuffer(function (err, buffer, info) {
                                    ^

TypeError: (0 , _sharp.default)(...)[sfunc] is not a function
    at vsharpIt (node_modules/vite-plugin-vsharp/d/vsharp.js:225:37)
    at node_modules/vite-plugin-vsharp/d/vsharp.js:139:13
    at Array.forEach (<anonymous>)
    at doSharp (node_modules/vite-plugin-vsharp/d/vsharp.js:136:25)
    at node_modules/vite-plugin-vsharp/d/vsharp.js:144:11
    at next (node_modules/vite-plugin-vsharp/d/vsharp.js:71:25)
    at node_modules/vite-plugin-vsharp/d/vsharp.js:82:11
    at FSReqCallback.oncomplete (node:fs:205:5)

Node.js v18.3.0
```

Thank you so much for your work on this plugin.

**Comment by nsouto** [comment]
While further investigating, I believe it's related to how it's picking up the files on my project, which is Laravel based.

I'll keep updating this thread with my findings

**Comment by nsouto** [comment]
While messing with this, I figured out that this is running before the static images are copied into the out folder, meaning:

I'm using a plugin viteStaticCopy to copy some images from one folder into my projects public folder so they are accessible to the application, however this plugin runs at the same time as viteStaticCopy which makes things hard because the files have are not there yet.

I changed the plugin to read a list of files from the original folder where they will be copied from, now the problem is not all files have been copied and as such the plugin breaks with a file not found.

Not sure if I explained it proper, but basically even after adding the `enforce: 'post'` to the plugin it seems to be just running alongside the others.

Any pointers would be appreciated, I will continue to investigate but would really appreciate some feedback when you have the time.

Thanks

**Comment by jw-12138** [comment]
@nsouto hello there, sorry for the slow response. having read about your thread i realize that this might not be the problem of the plugin.

first, you can try to add `enforce: pre` to the copy plugin and `enforce: post` to the vsharp plugin at the same time, if that still doesn't work, i recommend you to use other tools (like [Gulp](https://gulpjs.com/)) to integrate the workflow of your project.


here is a short example that might help you a little bit.

1. install `gulp` with npm

```bash
npm i gulp -D
```


2. add `gulpfile.js` to the root of your project

```javascript
const gulp = require('gulp')
const exec = require('child_process').exec

function copyImages() {
  let glob = ['public/images', 'someOtherFolder/blahblah.jpg']
  return gulp.src(glob)
    .pipe(gulp.dest('dist/images'))
}

function viteBuild(cb) {
  exec('npx vite build', function (err, stdout, stderr) {
    console.log(stdout)
    console.log(stderr)
    cb(err)
  })
}

exports.build = gulp.series(copyImages, viteBuild)
```

3. modify scripts in your `package.json`
```diff
 "scripts": {
+  "build": "gulp build"
-  "build": "vite build"
 }
```

4. don't forget to disable the copy plugin in `vite.config.js`, now try `npm run build` again.

good luck man!😉

**Comment by plakhin** [comment]
@nsouto. I'm also using Vite to copy static assets from `/resources/img` in Laravel project. I've solved the issue with this config option:
```diff
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
        vsharp({
+           excludePublic: ["public/build/*"],
        }),
    ],
```
