### ISSUE TITLE
Add resize support

### ISSUE THREAD

**Issue by septatrix** [jw-12138/vite-plugin-vsharp#6]
It does not seem like it is currently supported. However, it would be really great to use. This way one can add the full res images and limit the output resolution without having to resize them beforehand manually.

**Comment by jw-12138** [comment]
@septatrix thanks for the advice, I'll give it a look!

**Comment by jw-12138** [comment]
https://www.npmjs.com/package/vite-plugin-vsharp/v/1.2.0

@septatrix vite-plugin-vsharp version 1.2.0 has added image resizing support, you can use it like this:

```javascript
// vite.config.js

import vsharp from "vite-plugin-vsharp"

export default ({
  plugins: [
    vsharp({
      width: 800,
      height: 800,
      scale: 0.8
    })
  ]
})
```

note that `scale` will overwrite both `width` and `height` property.
